config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'session/new'
  resources :microposts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  resources :users do 
    member do
      get :following, :followers
    end
  end    

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'register', to:'users#new', as:'register'
  get 'login', to:'sessions#new', as:'login'
  post 'login', to:'sessions#create', as:'sign_in'
  delete 'logout', to:'sessions#destroy', as:'logout'

  root 'static_pages#home'


end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  before_action :get_user, only: [:edit, :update]
  before_action :valid_user, only: [:edit, :update]
  before_action :check_expiration, only: [:edit, :update]
  
  def new
  end

  def create
    @user = User.find_by(email: params[:password_resets][:email].downcase)
    if @user
      @user.create_reset_digest
      @user.send_password_reset_email
      flash[:info] = "Email sent with password reset instructions"
      redirect_to root_path
    else  
      flash[:danger] = "Email address not found"
      redirect_to new_password_reset_path
    end  
  end

  def edit
  end

  def update
    if params[:user][:password].empty?
      @users.errors.add(:password, "can't be empty" )
      render 'edit'
    elsif @user.update(user_params)
      log_in @user
      @user.update_attribute(:reset_digest, nil)
      flash[:success] = "Password has been reset"
      redirect_to @user
    else 
      render 'edit'
    end 
  end

  private
    
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  
    def get_user
      @user = User.find_by(email: params[:email])      
    end

    def valid_user
      unless @user && @user.activated? && @user.authenticated?(:reset, params[:id])
        redirect_to root_url        
      end
    end
    
    def check_expiration
      if @user.password_reset_expired?
        flash[:danger] = "Password reset has expired"
        redirect_to new_password_reset_url
      end
    end
    
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Reset password</h1>

<%= form_with(model: @user, url: password_reset_path(params[:id]), local: true) do |form| %>

  <% render 'layouts/error_messages', object: form.object %>

  <%= hidden_field_tag :email, @user.email %>

  <div class="m-3">
    <%= form.label :password, class:"input-label" %>
    <%= form.password_field :password, class:"form-control input-field" %>
  </div>

  <div class="m-3">
    <%= form.label :password_confirmation, "Confirmation", class:"input-label" %>
    <%= form.password_field :password_confirmation, class:"form-control input-field" %>
  </div>

  <div class="m-3">
    <%= form.submit "Update password", class:"btn btn-primary" %>
  </div>
<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot your password</h1>

<%= form_with(url: password_resets_path, scope: :password_reset, local: true) do |form| %>
  <% render 'layouts/error_messages', object: form.object %>
  
  <div class="m-3">
    <%= form.label :email, class:"input-label" %>
    <%= form.text_field :email, class:"form-control input-field" %>
  </div>

  <div class="m-3">
    <%= form.submit "Submit", class:"btn btn-primary" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to login", login_path, class:"btn btn-secondary" %>
</div>