config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'session/new'
  resources :microposts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  resources :users do 
    member do
      get :following, :followers
    end
  end    

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'register', to:'users#new', as:'register'
  get 'login', to:'sessions#new', as:'login'
  post 'login', to:'sessions#create', as:'sign_in'
  delete 'logout', to:'sessions#destroy', as:'logout'

  root 'static_pages#home'


end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  default_scope -> {order(created_at: :desc)}

  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum:140 }
  validates :image, content_type: {in: %w[image/jpeg image/png image/gif], message: "must be a valid image format"}, size: { less_than: 5.megabytes, message: "should be less than 5 MB"}

  def display_image
    image.variant(reisze_to_limit: [500, 500])
  end

end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: %i[ show edit update destroy ]
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy]

  # GET /microposts or /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1 or /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts or /microposts.json
  def create
    @micropost = current_user.microposts.build(micropost_params)
    
    if params[:micropost][:image]
      @micropost.image.attach(params[:micropost][:image])
    else
      @micropost.image.attach(io: File.open(Rails.root.join('app', 'assets', 'images', 'rails.png')), filename: 'rails.png', content_type: 'image/png')
    end


      if @micropost.save
        flash[:success] = "Micropost created!"
        redirect_to root_path
      else
        @feed_items = current_user.feed.paginate(page: params[:page])
        redirect_to root_path
      end
  end

  # PATCH/PUT /microposts/1 or /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to micropost_url(@micropost), notice: "Micropost was successfully updated." }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1 or /microposts/1.json
  def destroy
    @micropost.destroy
    flash[:danger] = "Micropost was successfully destroyed."
    redirect_to request.referrer || root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def micropost_params
      params.require(:micropost).permit(:content, :image)
    end

    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      if @micropost.nil?
        redirect_to root_path
        flash[:danger] = "wrong user"
      end
    end
    
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<div id="<%= dom_id micropost %>" class="my-3">
  <div class="row" style="text-align:left">
    <div class="col-6">
    <%= image_tag micropost.image, class:"img-fluid img-responsive p-2" if micropost.image.attached? %>
    </div>  
    <div class="col-6 my-auto">
      <p><%= micropost.content %></p>
      <p> 
        <strong>User:</strong>
        <%= micropost.user_id %>
      </p>
    </div> 
  </div>  

  <% if micropost.user_id == current_user.id %>
    <div class="d-flex flex-row justify-content-center">
      <%= link_to "Edit", edit_micropost_path(micropost), class:"btn btn-warning mx-2" %>
      <%= button_to "Delete", micropost, method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this micropost?' }, class:"btn btn-danger mx-2" %>
    </div>
  <% end %>

</div><hr>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Show this micropost", @micropost %> |
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Microposts</h1>

<div id="microposts">
  <% @microposts.each do |micropost| %>
    <%= render micropost %>
    <p>
      <%= link_to "Show this micropost", micropost %>
    </p>
  <% end %>
</div>

<%= link_to "New micropost", new_micropost_path %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/show.html.erb
<%= render @micropost %>

<div>
  <%= link_to "Edit this micropost", edit_micropost_path(@micropost) %> |
  <%= link_to "Back to microposts", microposts_path %>

  <%= button_to "Destroy this micropost", @micropost, class:"btn btn-danger", method: :delete, data: { turbo_confirm: 'Are you sure you want to delete this micropost?' } %>
</div>