config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'session/new'
  resources :microposts
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :relationships, only: [:create, :destroy]

  resources :users do 
    member do
      get :following, :followers
    end
  end    

  get 'static_pages/home'
  get 'static_pages/help'
  get 'static_pages/about'

  get 'register', to:'users#new', as:'register'
  get 'login', to:'sessions#new', as:'login'
  post 'login', to:'sessions#create', as:'sign_in'
  delete 'logout', to:'sessions#destroy', as:'logout'

  root 'static_pages#home'


end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
    <div style="color: red">
      <h2>The form contains <%= pluralize(object.errors.count, "error") %></h2>

      <ul>
        <% object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
<%end%>

app/views/layouts/_feed.html.erb
<div>
    <% if @feed_items.any? %>
        <ol class="microposts">
            <%= render @feed_items%>
        </ol>
        <%= will_paginate @feed_items, params: { controller: :static_pages, action: :home} %>
    <% end %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %> m-5" role="alert">
        <%= message %>
    </div><br>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="container-fluid bg-secondary m-0 p-5">
    <div class="row">
        <div class="col-4 my-auto">
          <%= image_tag "rails.png", class:"img-fluid" %>
        </div>
        <div class="col-4 my-auto text-center">
          <p>copyrigth @ 2022 by Joe Mazloum</p>
        </div>
        <div class="col-4 my-auto">
          <ul>
            <li>facebook</li>
            <li>instagram</li>
            <li>twitter</li>
          </ul>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
    <nav class="navbar navbar-expand-lg bg-secondary">
        <div class="container-fluid">
          <%= link_to "Home", root_path, id: "Logo" ,class: "navbar-brand" %>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <li><%= link_to "Home", static_pages_home_path, class: "nav-link" %></li>
              </li>
              <li class="nav-item">
                <li><%= link_to "About", static_pages_about_path, class: "nav-link" %></li>
              </li>
              <li class="nav-item">
                <li><%= link_to "Help", static_pages_help_path, class: "nav-link" %></li>
              </li>
              <li class="nav-item">
                <li><%= link_to "Users", users_path, class: "nav-link" %></li>
              </li>
            </ul>

            <div class="d-flex">
              <% if logged_in? %>
                  <%= link_to "Profile", current_user, class: "nav-link mx-2 btn btn-secondary" %>
                  <%= button_to "Logout", logout_path, method: :delete, class: "nav-link mx-2 btn btn-secondary" %>
              <% else %>
                <%= link_to "Login", login_path, class: "nav-link mx-2 btn btn-secondary" %>
                <%= link_to "Register", register_path, class: "nav-link mx-2 btn btn-secondary" %>
              <% end %>
            </div>
        </div>
    </nav>
</header>

app/views/layouts/_micropost_form.html.erb
<div class="card p-5">
    <%= form_with(model: @micropost, local: true) do |form| %>
        <% render 'layouts/error_messages', object: form.object %>

        <div>
            <%= form.text_area :content, placeholder:"Compose new Micropost", class:"input-field form-control" %>
        </div><br>

        <div>
            <%= form.file_field :image, class:"form-control input-field", accept: "image/jpeg,image.gif,image/png" %>
        </div>

        <div>
            <%= form.submit "Post", class:"btn btn-primary px-5 m-5" %>
        </div>
    <% end %>
</div>

<script type="text/javascript">
    $("#micropost_image").bind("change", function(){
        const size_in_megabytes = this.files[0].size/1024/1024;
        if (size_in_megabytes > 5) {
            alert("Maximum file size is 5MB. Please choose a smaller file.");
            $("#micropost_image").val("")
        }
    });
</script>

app/views/layouts/_stats.html.erb
<% @user ||= current_user %>
<div class="row text-center m-2">
    <div class="col-4">
        Following : <%= current_user.following.count %>
    </div>
    <div class="col-4">
        Followers : <%= current_user.followers.count %>
    </div>
    <div class="col-4">
        <% unless current_user?(@user) %>
            <% if current_user.following?(@user) %>
                <%= render "unfollow" %>
            <% else %>
                <%= render "follow" %>
            <% end %>
        <% end %>
    </div>    
</div>

app/views/layouts/_user_info.html.erb
<div class="card p-5">
    <h1><%= current_user.name %></h1>
    <h2><%= current_user.email %></h2>
    <h3>Microposts: <%= current_user.microposts.count %></h3>
    <%= link_to "View my profile", current_user, class:"btn btn-primary" %>
    <%= render "layouts/stats" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </head>

  <body class="container-fluid p-0 m-0">
    <%= render "layouts/header" %>

    <%= render "layouts/flash" %>

    <div class="container-fluid bg-light p-2 py-5 text-center">
      <%= yield %>
    </div>

    <%= render "layouts/footer" %>
  </body>
</html>